### PR TITLE
feat: TagExtractor

### PR DESCRIPTION
**Pull request by GeopJr**
fix: #880 

I tried out different ways to do this and honestly this is probably the best.

- Extracting while parsing the HTML

The way libxml2 traverses through a doc is unpredictable (aka, when it reaches an anchor, you can't exactly get the content, you have to go through it and usually the `#` character and the hashtag name are in different elements). That makes it impossible to detect that an anchor is a hashtag quickly and before parsing and appending it. Same thing for detecting if the last paragraph only has hashtags.

The structure also depends on the backend.

- Extracting them afterwards by parsing the pango markup

While we now have a predictable structure, the same issue as above is still present. It becomes too difficult to reliably detect if the last paragraph is only made of hashtag anchors.

- Current solution

Regex. (Anchors are predictable as it's being ran on the converted HTML)

https://github.com/user-attachments/assets/6bb4f161-a3f0-4757-89d5-cb5b6c672e18

### CODE REVIEW

**Comment by GeopJr** [comment]
> it'd be good to avoid the different widths

(you are aware of flowbox' width situation, where all columns have the same width which is the biggest item's. So the widths will be different when there are multiple rows)

> but maybe we could do something like the Mastodon web UI and only show 4 by default, and the rest in a popover or something

The video is a bit quick but the implementation is the same as mastodon-web. It shows the first 3 and then I click the 'Show 5 More' button which causes them all to appear. No opinion on popover or even dialog

Here's some different styles:

<details><summary>Smaller font</summary>

Screenshot From 2024-10-08 11-37-16

</details>

<details><summary>Less padding + Smaller font</summary>

Screenshot From 2024-10-08 11-37-10

</details>

<details><summary>Normal font weight</summary>

Screenshot From 2024-10-08 11-36-32

</details>

<details><summary>Normal font weight + Less padding</summary>

Screenshot From 2024-10-08 11-36-23

</details>

<details><summary>Less padding</summary>

Screenshot From 2024-10-08 11-36-12

</details>

**Comment by bragefuglseth** [comment]
> (you are aware of flowbox' width situation, where column items have the same width which is the biggest item's. So the widths will be different when there are multiple rows)

FYI: [this just landed in libadwaita’s main branch](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.WrapBox.html)

**Comment by GeopJr** [comment]
Should I port it over? I have many use cases for WrapBox that are currently using FlowBox here

**Comment by bragefuglseth** [comment]
Sure, it would be good to get some in-the-wild usage of the widget early on! And it seems like an obvious choice for this particular thing.

**Comment by GeopJr** [comment]
After spending some time porting it, I'm not sure if I want to continue.

We could use LabelWithWidgets in the meantime however:


https://github.com/user-attachments/assets/eb821f0e-0d2d-4bca-857b-a53b5967fbf4

since it's not really made just for custom emojis, but for any widget in general

**Comment by bragefuglseth** [comment]
That works for now (with more space between the elements, haha)

**Comment by GeopJr** [comment]
Performance is terrible, I'll stick to flowbox for now :shrug: :(

**Comment by bertob** [comment]
> Less padding + Smaller font

This one looks good to me!

> After spending some time porting it, I'm not sure if I want to continue.

If you encounter any issues with WrapBox, now would be a great time to provide feedback :)

**Comment by GeopJr** [comment]
> If you encounter any issues with WrapBox, now would be a great time to provide feedback :)

Nothing to do with WrapBox itself! Porting it to Vala is quite the challenge due to some incompatibilities between C and Vala and ripping it out of libadwaita as is requires copying over a lot of other things, so it's probably best to wait for 1.7

**Comment by bertob** [comment]
Ah yeah, that makes sense :+1:

**Pull request merged**
