### PR TITLE
feat(mv): Few small clapper code enhancements

### PR DESCRIPTION
**Pull request by Rafostar**
Few small changes/enhancements for Clapper MediaViewer code:
* Enable loop for GIF videos
* Complement MPRIS args
* Do not show controls for GIFV

### CODE REVIEW

**Comment by GeopJr** [comment]
LGTM, thanks!

**Comment by Rafostar** [comment]
My main aim here was to add loop for GIFV which was missing. I also changed for GIFV to not show bottom controls panel as browsers do not do that and I think this is right thing to do, but if you disagree let me know and I can drop this commit.

**Comment by GeopJr** [comment]
Oh no, it's great, you actually fixed #435 (partially)! (Removing Gtk.Video's controls would be too annoying so I never did it)

That being said, that change might be changed in the future if users complain because Mastodon has video limitations.

On Mastodon you can only post either one video or 4(+) attachments, so if you want to post videos and other attachments, users convert them to gifs. Those gifs are sometimes too long and technical and could benefit from video controls, e.g. the first attachment here: https://mastodon.social/@haeckerfelix/112656595629880944 ... But, overall treating them as gifs is the best option!

**Comment by Rafostar** [comment]
On the side note: The looping should be "seamless" (without hiccups) after combined with #1010. Then video will be streamed at the beginning followed by looping by using cached file exclusively. But these two PRs are not depending on each other as that part is handled transparently inside Clapper 0.8 so they can go in in any order.

**Pull request merged**
