### PR TITLE
feat: 0.9.0

### PR DESCRIPTION
**Pull request by GeopJr**
TODO:

- [x] appstream release notes
- [x] git release notes
- [x] fedi release notes, screenshots
- [ ] release
- [ ] flatpak manifest on flathub
- [ ] take a break

fix: #1155 
fix: #1098
fix: #1278 

```
# Added

- Audio Visualizer (#1099)
- Focus Picker (#1101)
- Scheduled Posts (#1209)
- Draft Posts (#1213)
- Bold search query in results (#1085)
- Mute expiration and notification hiding switch (#1106)
- Verified Authors section on preview cards (#1112)
- Link discussion timelines on explore tab news (#1113)
- Accent colors and other GNOME 47 changes (#1117)
- Numeric style for counters (#1124)
- Adw.Spinners (#1126)
- Attachment thumbnail in alt text dialog (#1128)
- Custom picture widget that can display thumbnails at their defined focus position (#1129)
- tuba://share (#1131)
- Removed the pre 0.8 cache cleaner (#1137)
- Muting your own posts (#1134)
- Copy attachment on <kbd>Ctrl</kbd><kbd>C</kbd> in the Media Viewer (#1148)
- Auto-fill author button in Advanced Search Dialog (#1147)
- Hashtag extracting from the end of a post to a separate section (#1149)
- Removed GL renderer preference (#1150)
- Poll animations (#1161)
- Poll show and refresh results buttons (#1160)
- Full emoji reaction and stats support when possible (#1145)
- Opt-in anonymous preference popularity analytics (#1166)
- Improved the profile posts, replies, media filter UX (#1189)
- Use TextView for the alt text dialog (#1195)
- Sync post language and spellchecker language (#1201)
- #FediWrapped (#1198)
- Account suggestions for new fediverse users (#1241)
- Clean up timelines when blocking / muting accounts (#1206)
- Moved accounts note (#1216)
- Dedicated quote button when appropriate (#1215)
- Viewing which ones of the people you follow also follow an account
- Refreshing outdated profile info on cached users (#1174)
- Placing favorite lists to the sidebar (#1244)
- Simpler UX for list member removals (#1255)
- Bubble timeline on supported backends (#1253)
- Moved notification policy settings to the notification view settings dialog (#1252)
- Hide window controls from the Media Viewer to avoid accidentally closing Tuba (#1221)
- Many accessibility improvements (#1226)
- Account birthday style (#1205)
- Thread root post refresh on load (#1266)
- Removed timeline refreshing on network change (#1196, thanks [at]farao)
- Avatar and Header alt text viewing and editing on supported backends (#1133)
- Improved UI of the New Account Dialog to better match the HIG (#1156)
- Handle `status` notification type (#1107)
- Handle `moderation_warning` notification type (#1204)
- Window icon as a fallback (#1097, thanks [at]City-busz)

# Fixed

- Alt text publishing on Akkoma (#1120)
- Dialog titles not following the HIG (#1135)
- Jarring Media Viewer scale animation states (#1125)
- Completion providers returning incorrect results due to the prefix in some backends (#1169)
- Crashes due to custom widgets types not being available sometimes (#1170)
- Floating button area being unclickable and unscrollable (#1180)
- Headerbar having a big minimum width (#1184)
- Use UriLauncher when appropriate (#1211)
- Utility dialogs headerbar UX not following the HIG (#1238)
- List creation and editing on Akkoma (#1254)
- Media Viewer auto-hide timeout match Gtk.Video's (#1262, thanks [at]rmader)
- Filter creation and editing on GoToSocial
- Timestamp tooltip text format not being converted to the local timezone from UTC (#1275)
- RTL versions of icons not being set or missing (#1277)

**Full Changelog**: https://github.com/GeopJr/Tuba/compare/v0.8.4...v0.9.0
```

### CODE REVIEW

**Comment by LukaszH77** [comment]
I this the longest changelog so far? o.O

**Comment by GeopJr** [comment]
Probably because it took a lot longer to release :( Last minor release was 6 months ago, while all the others previously usually had a 2 month gap between them :shrug: 

This release did have some 'big' features though (audio visualizer, focus picker stuff, draft/scheduled posts, fediwrapped) so it was worth it

**Comment by LukaszH77** [comment]
I didn't even realize that so much time has passed since the last release, mostly because I update Tube almost after every new commit :)

**Comment by GeopJr** [comment]
Lol I found 2 other bugs while taking fedi screenshots

**Pull request merged**
